{{- if and .Values.serviceAccount.create (include "khulnasoft.restarter.enabled" .) }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.serviceAccount.name }}-restarter
  namespace: {{ .Release.Namespace }}
{{- end -}}
