{{- if semverCompare "<1.25-0" (include "khulnasoft.kubeVersion" .) -}}
{{- if .Values.rbac.create -}}
{{- if .Values.rbac.pspEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "khulnasoft.fullname" . }}-psp
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "khulnasoft.fullname" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
{{- end -}}
