{{- if semverCompare "<1.25-0" (include "khulnasoft.kubeVersion" .) -}}
{{- if .Values.rbac.create -}}
{{- if .Values.rbac.pspEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "khulnasoft.fullname" . }}-psp
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "khulnasoft.fullname" . }}-psp
{{- end -}}
{{- end -}}
{{- end -}}
