{{- if .Values.serviceAccount.create -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
