{{- $secretk8sState := include "khulnasoft.k8sState.configs.secret" . }}
{{- if and .Values.k8sState.enabled $secretk8sState }}
---
apiVersion: v1
kind: Secret
metadata:
  name: khulnasoft-conf-k8s-state
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretk8sState | indent 2 }}
{{- end }}
