{{- $configmapParent := include "khulnasoft.parent.configs.configmap" . }}
{{- if and .Values.parent.enabled $configmapParent }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: khulnasoft-conf-parent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ $configmapParent | indent 2 }}
{{- end }}
