{{- $secretParent := include "khulnasoft.parent.configs.secret" . }}
{{- if and .Values.parent.enabled $secretParent }}
---
apiVersion: v1
kind: Secret
metadata:
  name: khulnasoft-conf-parent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "khulnasoft.name" . }}
    chart: {{ template "khulnasoft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretParent | indent 2 }}
{{- end }}
